-- Run manually with ACCOUNTADMIN after initial deployment
-- These grants require privileges beyond the CICD role
USE ROLE ACCOUNTADMIN;
USE DATABASE ECO_DEV;
USE SCHEMA ECOS_RAW_V001;

GRANT READ ON STAGE ECOS_RAW_ST_DOC_MT TO ROLE BANK1_ROLE;
GRANT READ ON STAGE ECOS_RAW_ST_DOC_MT TO ROLE BANK2_ROLE;

GRANT SELECT ON VIEW ECOS_RAW_VW_STAGE_FILES_DOWNLOAD_MT TO ROLE BANK1_ROLE;
GRANT SELECT ON VIEW ECOS_RAW_VW_STAGE_FILES_DOWNLOAD_MT TO ROLE BANK2_ROLE;

GRANT USAGE ON PROCEDURE ECOS_RAW_SP_REGISTER_FILE(VARCHAR, VARCHAR, VARCHAR, FLOAT) TO ROLE BANK1_ROLE;
GRANT USAGE ON PROCEDURE ECOS_RAW_SP_REGISTER_FILE(VARCHAR, VARCHAR, VARCHAR, FLOAT) TO ROLE BANK2_ROLE;

GRANT USAGE ON DATABASE ECO_DEV TO ROLE BANK1_ROLE;
GRANT USAGE ON DATABASE ECO_DEV TO ROLE BANK2_ROLE;

GRANT USAGE ON SCHEMA ECO_DEV.ECOS_RAW_V001 TO ROLE BANK1_ROLE;
GRANT USAGE ON SCHEMA ECO_DEV.ECOS_RAW_V001 TO ROLE BANK2_ROLE;

GRANT USAGE ON WAREHOUSE MD_TEST_WH TO ROLE BANK1_ROLE;
GRANT USAGE ON WAREHOUSE MD_TEST_WH TO ROLE BANK2_ROLE;

CREATE CONTACT IF NOT EXISTS DataSteward EMAIL_DISTRIBUTION_LIST = 'datasteward@snowflake.com';
CREATE CONTACT IF NOT EXISTS Support EMAIL_DISTRIBUTION_LIST = 'datasteward@snowflake.com';
CREATE CONTACT IF NOT EXISTS Approver EMAIL_DISTRIBUTION_LIST = 'datasteward@snowflake.com';
CREATE CONTACT IF NOT EXISTS "Security & compliance" EMAIL_DISTRIBUTION_LIST = 'datasteward@snowflake.com';

ALTER DATABASE ECO_DEV SET CONTACT
    STEWARD         = DataSteward,
    SUPPORT         = Support,
    ACCESS_APPROVAL = Approver;
