USE ROLE ACCOUNTADMIN;
USE WAREHOUSE MD_TEST_WH;
USE DATABASE ECO_DEV;
USE SCHEMA ECOS_RAW_V001;

CREATE OR REPLACE PROCEDURE ECOS_RAW_SP_REGISTER_FILE(
    TENANT_ID  VARCHAR,
    FILE_PATH  VARCHAR,
    FILE_NAME  VARCHAR,
    FILE_SIZE  FLOAT
)
RETURNS VARCHAR
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS
'var q = String.fromCharCode(39);
var db = snowflake.createStatement({sqlText: "SELECT CURRENT_DATABASE()"}).execute();
db.next();
var schema = snowflake.createStatement({sqlText: "SELECT CURRENT_SCHEMA()"}).execute();
schema.next();
var fullSchema = db.getColumnValue(1) + "." + schema.getColumnValue(1);

var mergeSql =
    "MERGE INTO " + fullSchema + ".ECOS_RAW_TB_STAGE_FILES_MT t " +
    "USING (SELECT " + q + TENANT_ID + q + " AS TENANT_ID, " + q + FILE_PATH + q + " AS FILE_PATH) s " +
    "ON t.TENANT_ID = s.TENANT_ID AND t.FILE_PATH = s.FILE_PATH " +
    "WHEN MATCHED THEN UPDATE SET " +
    "    t.FILE_SIZE = " + FILE_SIZE + ", " +
    "    t.FILE_NAME = " + q + FILE_NAME + q + ", " +
    "    t.REFRESHED_AT = CURRENT_TIMESTAMP() " +
    "WHEN NOT MATCHED THEN INSERT (TENANT_ID, FILE_NAME, FILE_PATH, FILE_SIZE) " +
    "VALUES (" + q + TENANT_ID + q + ", " + q + FILE_NAME + q + ", " + q + FILE_PATH + q + ", " + FILE_SIZE + ")";

snowflake.execute({sqlText: mergeSql});
return "File registered: " + FILE_PATH + " for tenant: " + TENANT_ID;';

CREATE OR REPLACE SECURE VIEW ECOS_RAW_VW_STAGE_FILES_DOWNLOAD_MT AS
SELECT
    TENANT_ID,
    FILE_NAME,
    FILE_PATH,
    FILE_SIZE,
    LAST_MODIFIED,
    REFRESHED_AT,
    BUILD_STAGE_FILE_URL('@ECO_DEV.ECOS_RAW_V001.ECOS_RAW_ST_DOC_MT', FILE_PATH) AS DOWNLOAD_URL
FROM ECOS_RAW_TB_STAGE_FILES_MT;

CREATE OR REPLACE ROW ACCESS POLICY ECOS_RAW_PL_STAGE_FILES_MT
AS (TENANT_ID_ARG VARCHAR) RETURNS BOOLEAN ->
    CURRENT_ROLE() = 'ACCOUNTADMIN'
    OR CURRENT_ROLE() = TENANT_ID_ARG || '_ROLE'
    OR (
        CURRENT_ROLE() IS NULL
        AND EXISTS (
            SELECT 1
            FROM ECOS_RAW_TB_CONSUMER_ROLE_MAPPING
            WHERE CONSUMER_ACCOUNT = CURRENT_ACCOUNT()
              AND TENANT_ID        = TENANT_ID_ARG
        )
    );

ALTER VIEW ECOS_RAW_VW_STAGE_FILES_DOWNLOAD_MT
    ADD ROW ACCESS POLICY ECOS_RAW_PL_STAGE_FILES_MT ON (TENANT_ID);

GRANT READ ON STAGE ECOS_RAW_ST_DOC_MT TO ROLE BANK1_ROLE;
GRANT READ ON STAGE ECOS_RAW_ST_DOC_MT TO ROLE BANK2_ROLE;

GRANT SELECT ON VIEW ECOS_RAW_VW_STAGE_FILES_DOWNLOAD_MT TO ROLE BANK1_ROLE;
GRANT SELECT ON VIEW ECOS_RAW_VW_STAGE_FILES_DOWNLOAD_MT TO ROLE BANK2_ROLE;

GRANT USAGE ON PROCEDURE ECOS_RAW_SP_REGISTER_FILE(VARCHAR, VARCHAR, VARCHAR, FLOAT) TO ROLE BANK1_ROLE;
GRANT USAGE ON PROCEDURE ECOS_RAW_SP_REGISTER_FILE(VARCHAR, VARCHAR, VARCHAR, FLOAT) TO ROLE BANK2_ROLE;

GRANT USAGE ON DATABASE ECO_DEV TO ROLE BANK1_ROLE;
GRANT USAGE ON DATABASE ECO_DEV TO ROLE BANK2_ROLE;

GRANT USAGE ON SCHEMA ECO_DEV.ECOS_RAW_V001 TO ROLE BANK1_ROLE;
GRANT USAGE ON SCHEMA ECO_DEV.ECOS_RAW_V001 TO ROLE BANK2_ROLE;

GRANT USAGE ON WAREHOUSE MD_TEST_WH TO ROLE BANK1_ROLE;
GRANT USAGE ON WAREHOUSE MD_TEST_WH TO ROLE BANK2_ROLE;

CREATE CONTACT IF NOT EXISTS DataSteward EMAIL_DISTRIBUTION_LIST = '<steward@your-org.com>';
CREATE CONTACT IF NOT EXISTS Support EMAIL_DISTRIBUTION_LIST = '<support@your-org.com>';
CREATE CONTACT IF NOT EXISTS Approver EMAIL_DISTRIBUTION_LIST = '<approver@your-org.com>';
CREATE CONTACT IF NOT EXISTS "Security & compliance" EMAIL_DISTRIBUTION_LIST = '<compliance@your-org.com>';

ALTER DATABASE ECO_DEV SET CONTACT
    STEWARD         = DataSteward,
    SUPPORT         = Support,
    ACCESS_APPROVAL = Approver;
