-- Run manually with ACCOUNTADMIN after initial deployment.
-- These grants require privileges beyond the CICD role.
--
-- Account : zs28104.eu-central-1
-- Database: {{db}}
-- Schema  : {{schema}}
--

USE ROLE ACCOUNTADMIN;
USE DATABASE {{db}};
USE SCHEMA {{schema}};

GRANT USAGE ON DATABASE {{db}} TO ROLE BANK1_ROLE;
GRANT USAGE ON DATABASE {{db}} TO ROLE BANK2_ROLE;

GRANT USAGE ON SCHEMA {{schema}} TO ROLE BANK1_ROLE;
GRANT USAGE ON SCHEMA {{schema}} TO ROLE BANK2_ROLE;

GRANT USAGE ON WAREHOUSE {{wh}} TO ROLE BANK1_ROLE;
GRANT USAGE ON WAREHOUSE {{wh}} TO ROLE BANK2_ROLE;

GRANT READ ON STAGE ECOS_RAW_ST_DOC_MT TO ROLE BANK1_ROLE;
GRANT READ ON STAGE ECOS_RAW_ST_DOC_MT TO ROLE BANK2_ROLE;

GRANT WRITE ON STAGE ECOS_RAW_ST_DOC_MT TO ROLE BANK1_ROLE;
GRANT WRITE ON STAGE ECOS_RAW_ST_DOC_MT TO ROLE BANK2_ROLE;

GRANT SELECT ON VIEW ECOS_RAW_VW_STAGE_FILES_DOWNLOAD_MT TO ROLE BANK1_ROLE;
GRANT SELECT ON VIEW ECOS_RAW_VW_STAGE_FILES_DOWNLOAD_MT TO ROLE BANK2_ROLE;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA {{schema}} TO ROLE BANK1_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA {{schema}} TO ROLE BANK2_ROLE;

GRANT USAGE ON PROCEDURE ECOS_RAW_SP_REGISTER_FILE(VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, FLOAT) TO ROLE BANK1_ROLE;
GRANT USAGE ON PROCEDURE ECOS_RAW_SP_REGISTER_FILE(VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, FLOAT) TO ROLE BANK2_ROLE;

GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA {{schema}} TO ROLE BANK1_ROLE;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA {{schema}} TO ROLE BANK2_ROLE;

CREATE CONTACT IF NOT EXISTS DataSteward EMAIL_DISTRIBUTION_LIST = 'datasteward@snowflake.com';
CREATE CONTACT IF NOT EXISTS Support EMAIL_DISTRIBUTION_LIST = 'datasteward@snowflake.com';
CREATE CONTACT IF NOT EXISTS Approver EMAIL_DISTRIBUTION_LIST = 'datasteward@snowflake.com';
CREATE CONTACT IF NOT EXISTS "Security & compliance" EMAIL_DISTRIBUTION_LIST = 'datasteward@snowflake.com';

ALTER DATABASE {{db}} SET CONTACT
    STEWARD         = DataSteward,
    SUPPORT         = Support,
    ACCESS_APPROVAL = Approver;
