name: Update Local Repository and Run Sonar Scanner

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  pipeline:
    uses: zbrainiac-labs/DataOpsBackbone/.github/workflows/dataops-pipeline.yml@main
    with:
      SOURCE_DATABASE: ECO_DEV
      SOURCE_SCHEMA: ECOS_RAW_V001
      DCM_PROJECT_IDENTIFIER: ECO_DEV.ECOS_RAW_V001.SHARING_OBJECTS
      DCM_TARGET: DEV
    secrets: inherit
